version: '2'
services:
    buid:
        image: node
        volumes:
            - ./:/app
        command: bash -c "cd /app && npm install && npm run prod"
        container_name: star-build
    web:
        image: httpd:alpine
        container_name: star-web
        volumes:
            - ./web:/usr/local/apache2/htdocs
        ports:
            - 9866:80