version: '2'
services:
    buid:
        image: node
        volumes:
            - ./:/app
        command: bash -c "cd /app ; npm install ; npm rebuild node-sass ; npm run prod"
        container_name: star-build
    web:
        image: nginx:alpine
        container_name: star-web
        volumes:
            - ./web:/app
            - ./nginx.conf:/etc/nginx/conf.d/app.conf
        ports:
            - 80:80
